/**
 * @file genie_model_runtime.h
 * @brief IModelRuntime adapter for Qualcomm Genie (QAIRT) — NPU/HTP inference.
 *
 * This is the runtime that makes the product distinct: real NPU token
 * generation on Snapdragon, with the framework's commit fence and independent
 * stream verification wrapped around it.
 *
 * Design decisions and why:
 *
 *  1. dlopen(libGenie.so) rather than link-time dependency.
 *     The same sparx binary must run on a host without the Qualcomm stack
 *     (where it reports a clean "NPU unavailable" and falls back to llama.cpp)
 *     and on-device where it uses the NPU. A link-time dependency would make
 *     the binary refuse to start on the former.
 *
 *  2. GenieDialog_query with a token callback, NOT spawning genie-t2t-run.
 *     Spawning the sample binary means: no streaming into our sink, a process
 *     launch per turn (~300ms), no KV cache reuse across turns, and parsing
 *     human-readable stdout. The in-process API gives token-level callbacks
 *     and a persistent dialog handle.
 *
 *  3. The dialog handle is retained across invocations for KV cache reuse,
 *     and reset when the framework signals a new session.
 *
 * OPEN RISK (documented, not resolved): if Genie's callback delivers
 * unverified draft tokens under speculative decoding and later retracts them,
 * the framework's stream accumulator would see deltas that do not concatenate
 * to the final raw_output and would report INFERENCE_STREAM_OUTPUT_DIVERGED.
 * This runtime therefore treats the *final* sentence-complete callback as the
 * authoritative delta source and buffers partial ones. This must be verified
 * on-device before the ABI is frozen.
 */

#pragma once

#include "master_agent/inference/inference_framework.h"

#include <cstdint>
#include <memory>
#include <mutex>
#include <string>

namespace master_agent::inference {

struct GenieConfig {
    /// Path to the Genie dialog config JSON (generated by sparx deploy).
    std::string config_path;
    /// Directory containing libGenie.so. If empty, uses the system loader path.
    std::string library_dir;
    /// Detected SoC id, used only for diagnostics in error messages.
    std::uint32_t soc_id = 0;
    /// HTP architecture string (e.g. "v81"), diagnostics only.
    std::string dsp_arch;
    /// Runtime tag used in model_digest validation.
    std::string runtime_tag = "genie-htp";
    /// When true, keeps the dialog handle across invocations for KV reuse.
    bool reuse_dialog = true;
};

/// Reports which parts of the Qualcomm stack were found. Drives `sparx doctor`
/// output and the fallback decision, so the user learns *why* the NPU is not
/// being used rather than silently getting CPU speed.
struct GenieAvailability {
    bool library_found = false;
    bool symbols_resolved = false;
    bool config_valid = false;
    std::string library_path;
    std::string detail;

    bool usable() const {
        return library_found && symbols_resolved && config_valid;
    }
};

/**
 * @brief Runs inference on the Hexagon NPU through Genie's C API.
 *
 * Streaming maps naturally: GenieDialog_query invokes our callback once per
 * generated token span, and each becomes one InferenceChunk. The framework
 * accumulates them independently and compares against raw_output at commit
 * time, so an NPU-side bug that drops or duplicates tokens is caught rather
 * than silently reaching the decision path.
 */
class GenieModelRuntime final : public IModelRuntime {
public:
    explicit GenieModelRuntime(GenieConfig config);
    ~GenieModelRuntime() override;

    /// Probes for libGenie.so and its symbols without creating a dialog.
    /// Safe to call on a host with no Qualcomm stack.
    static GenieAvailability probe(const std::string& library_dir = {});

    std::uint32_t requiredWorkUnits(
        const InferenceRequest& request) const override;

    std::string runtimeTag() const override { return config_.runtime_tag; }

    Result<InferenceOutput> infer(
        const InferenceRequest& request,
        const RuntimeInvocationSeal& seal) override;

    bool supportsStreaming() const override { return true; }

    Result<InferenceOutput> inferStream(
        const InferenceRequest& request,
        const RuntimeInvocationSeal& seal,
        const InferenceStreamSink& sink) override;

    /// True when the dialog handle is live and ready to accept a query.
    bool isReady() const;

    /// Releases the dialog and reloads config. Used when the model changes.
    Status reload(const std::string& config_path);

    const GenieAvailability& availability() const { return availability_; }

private:
    struct Impl;  // holds the dlopen handle, function pointers, and dialog

    Status validateSeal(const InferenceRequest& request,
                        const RuntimeInvocationSeal& seal) const;

    void echoSeal(InferenceOutput& out,
                  const RuntimeInvocationSeal& seal,
                  const InferenceRequest& request) const;

    /// Creates the dialog handle. Idempotent.
    Status ensureDialog();
    void releaseDialog();

    GenieConfig config_;
    GenieAvailability availability_;
    std::unique_ptr<Impl> impl_;
    mutable std::mutex mutex_;
};

}  // namespace master_agent::inference
