# Project-wide Gradle settings

# AndroidX
android.useAndroidX=true

# NDK parallel builds
android.enableCmakeNdkBuild=true

# Kotlin code style (official = Android Kotlin Styleguide)
kotlin.code.style=official

# JVM target
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Non-transitive R classes for better build performance
android.nonTransitiveRClass=true
