function(checked)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Consumer check failed: ${ARGV}")
    endif()
endfunction()
set(stage "${BUILD_DIR}/consumer-stage")
set(relocated "${BUILD_DIR}/consumer-relocated")
file(REMOVE_RECURSE "${stage}" "${relocated}" "${BUILD_DIR}/consumer-build")
checked("${CMAKE_COMMAND}" --install "${BUILD_DIR}" --prefix "${stage}" --config "${TEST_CONFIG}")
file(RENAME "${stage}" "${relocated}")
checked("${CMAKE_COMMAND}" -S "${SOURCE_DIR}/tests/consumer" -B "${BUILD_DIR}/consumer-build"
    "-DCMAKE_PREFIX_PATH=${relocated}")
checked("${CMAKE_COMMAND}" --build "${BUILD_DIR}/consumer-build" --config "${TEST_CONFIG}")
checked("${CMAKE_CTEST_COMMAND}" --test-dir "${BUILD_DIR}/consumer-build" -C "${TEST_CONFIG}" --output-on-failure)
